CC = g++ -std=c++11
CFLAGS = -fpic
LDFLAGS=
LDLIBS = -lgsl -lgslcblas -lm -lboost_program_options -D_GLIBCXX_USE_CXX11_ABI=0
SOURCES= vessel.cpp matfun.cpp functions.cpp main_function.cpp 
OBJECTS=$(SOURCES:.cpp=.o)
EXECUTABLE=gnr_function

all: $(SOURCES) $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS)
	$(CC) $(LDFLAGS) $(OBJECTS) -o $@ $(LDLIBS)

.cpp.o:
	$(CC) $(CFLAGS) $< -c -o $@ $(LDLIBS)

clean:
	rm -f *.o *.mod *~ $(EXECUTABLE)

